### ISSUE TITLE
Stream events from go-audit files to s3 bucket

### ISSUE THREAD

**Issue by praneshvenkat** [mozilla/audit-go#13]
Hi,

Is there any way to stream events from go-audit log files to s3 bucket in realtime? Can you suggest how this can be achieved. Couldn't find any plugins relevant to this feature enabled with go-audit or will it be achieved only via any third party tools like logstash or anything else. Kindly suggest.

**Comment by ameihm0912** [comment]
@praneshvenkat there would not be currently

If you want S3 delivery, you could look at writing a small program that imports [libaudit-go](https://github.com/mozilla/libaudit-go) and does something like pushes the records to firehose (with configured s3 delivery)

**Comment by praneshvenkat** [comment]
@ameihm0912 Thanks for the quick response. We have wrote a script to do this task.
